### PR TITLE
Actions for nightly release

### PR DESCRIPTION
**Pull request by ShiriNmi1520**
## TODO Lists
- [x] Create nightly release
- [x] Check whatever master branch changed before create release
- [x] Include `gulp build` command
- [ ] Make `msbuild` to generate single executable for release
## Feature
Automatically create nightly release #11 
## Description
I've completed the workflow for creating nightly release at 2 AM (UTC+8) (GitHub Actions hosted runner use UTC)
At 2 AM, the workflow will fetch the latest built artefacts and update the nightly release title & content (You can modify the release title and  content in the yml file or just edit release info)

If you want, you can modify when will nightly release will be created (There's an expected delay if you using GitHub shared runner for the build, probably around 3 to 10 minutes)

P.S: The following screenshot date was yesterday from the day I created the pull request cause GitHub Actions use UTC as I mentioned before, I can modify it to use UTC +8 timezone or you can leave it to use UTC instead)

## Screenshot
image

### CODE REVIEW

**Comment by ShiriNmi1520** [comment]
About task number 2 I found a GitHub Action called [nightly-check](https://github.com/lukecarr/nightly-check) which is suitable for this task, but it requires further fix since my [workflow](https://github.com/ShiriNmi1520/Tiefsee4/actions/runs/5777658606) always failed after implementing it.
I've submitted a [PR](https://github.com/lukecarr/nightly-check/pull/4) to original repository and waiting for approved and pulled into main.

**Comment by ShiriNmi1520** [comment]
[nightly-check](https://github.com/lukecarr/nightly-check) approved my last pull request, adding check now.

**Comment by hbl917070** [comment]
The steps to export a zip file from Tiefsee are:
1. Run `gulp watch` in the `Tiefsee/www` directory to package ts, scss, ejs, and svg into static web pages.
2. Compile `Tiefsee4.sln` (`Tiefsee.csproj` already includes the syntax to copy the static web pages from `Tiefsee/www` to the output directory, but does not include automatic execution of gulp).
3. Go to the `runtimes` directory in the output directory and keep only `win-x64`, deleting all others (I'm not sure why these useless files are generated, I've already set the build target to win x64).

If you don't do step 3, you'll just have an extra 70M of useless files, but if you don't do step 1, Tiefsee.exe won't run.

So I'm not sure if this automation flow is feasible.

**Comment by ShiriNmi1520** [comment]
Thanks for the feedback, in my workflow, I did not include part executing `gulp watch` to generate packaged web pages.

About useless files mentioned in step 3 might be related to the `msbuild` command in workflow, according to I know `msbuild` will copy essential file that makes the program run into the output directory (Just like step 2 which copies static web pages into the output directory), there could be a way to tell `msbuild` to generate a single executable file and we can upload it to release which I will look into it later today

**Comment by hbl917070** [comment]
359843d
“gulp watch is a development mode that continuously monitors file changes, which may cause problems. 
I added another command gulp build, which will only be executed once.”

**Comment by ShiriNmi1520** [comment]
> 359843d
> 
> `gulp watch` is a development mode that continuously monitors file changes, which may cause problems. 
> 
> I added another command `gulp build`, which will only be executed once.
> 

Appreciation for updating, that definitely will help me to get things done 😀

**Comment by ShiriNmi1520** [comment]
I've completed adding `gulp build` during workflow and expect to complete `msbuild` part by weekend

**Comment by ShiriNmi1520** [comment]
I've also noticed that check nightly workflow was finished with error, I'll trying implement a patch on it before continue
image

**Pull request merged**
